Repository SAP/fundamental, pull requests merged in 2021-06, with the labels that each got.

#1617 chore: add commitlint, update changelog
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  .nvmrc
  .travis.yml
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
  commitlint.config.js
  netlify.toml
  package-lock.json
  package.json
Labels: Tools, dependencies

#1618 chore: add conventional-changelog-cli
  package-lock.json
  package.json
Labels: dependencies

#1621 chore: update bump version
  ci-scripts/publish-rc.sh
  ci-scripts/publish.sh
  package-lock.json
  package.json
Labels: Tools

#1623 docs(deps): create conference page - initial state
  docs/fundamental-conf.html
  docs/images/land-page-assets/fundamentalconf.png
Labels: fundamental-conf

#1624 chore(deps-dev): add in-solidarity to check inclusice language
  .github/in-solidarity.yml
Labels: Tools

#1625 chore(deps-dev): update in-solidarity.yml configuration
  .github/in-solidarity.yml
Labels: Tools
